PACS_HIS_RIS/urls.py
from django.contrib import admin
from django.urls import path,include

admin.site.site_header = "PACS HIS RIS Admin"
admin.site.site_title = "PACS HIS RIS Admin Portal"
admin.site.index_title = "Welcome to PACS HIS RIS Admin Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("home_app.urls")),
    path("accounts/",include("accounts.urls")),
    path("patient/",include("patient.urls")),
    path("lab_operator/",include("lab_operator.urls")),
    path("doctor/",include("doctor.urls")),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path,include
from .views import register_request,login_request,logout_request,account_nav
app_name = "accounts"
urlpatterns = [
    path("register", register_request, name="register"),
    path("login", login_request, name="login"),
    path("account_nav", account_nav, name="account_nav"),
    path("logout", logout_request, name="logout"),
]

doctor/urls.py
from django.urls import path
from .views import doctor_dashboard,prescribe,patient_not_found,previous_prescription,previous_prescriptions_details

app_name = "doctor"
urlpatterns = [
    path("dashboard",doctor_dashboard,name="doctor_dashboard"),
    path("prescribe",prescribe,name="prescribe"),
    path("patient_not_found",patient_not_found,name="patient_not_found"),
    path("previuos_prescriptions",previous_prescription,name="previous_prescription"),
    path("previuos_prescriptions_details/<int:id>",previous_prescriptions_details,name="previous_prescriptions_details"),
]

home_app/urls.py
from django.urls import path
from .views import test_view

app_name = "home_app"
urlpatterns = [
    path("",test_view,name="home")
]

home_app/models.py
from django.db import models

# Create your models here.

home_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

def test_view(request):
    return render(request,"index.html")

home_app/templates/base.html
<html>

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Bootstrap CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"> </head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
            <a href="../../../" class="navbar-brand"> PACS HIS RIS System</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu">
                <span class="navabar-toggler-icon"> <i class="fas fa-bars"></i></span>
            </button>

            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav ms-auto">
                    <!-- <li class="nav-item">
                        <a href="{% url 'accounts:register' %}" class="nav-link"> Sign Up </a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-link"> About </a>
                    </li> -->
                    <li class="nav-item">
                        <a href="{% url 'accounts:logout' %}" class="nav-link"> Logout </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="spacer my-5"></div>
    {% block content %} {% endblock %}
    <div class="spacer my-5"></div>
    <footer class="my-5 py-5 ">
        <div class="bg-dark text-light mt-5 p-5 text-center">
            <div class="container">
                <h3>Devloped for Telemedicine Lab, BME, KUET</h3>
            </div>
        </div>
    </footer>
    <!-- Optional Javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

home_app/templates/home.html
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
    {% block content %}{% endblock %}

    <!-- Optional Javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

home_app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Home </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" /> {% load static %}
    <link rel="stylesheet" href="{% static 'home_app/css/main.css' %}">

</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
            <a href="" class="navbar-brand"> PACS HIS RIS System</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu">
                <span class="navabar-toggler-icon"> <i class="fas fa-bars"></i></span>
            </button>

            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="{% url 'accounts:account_nav' %}" class="nav-link"> Login </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'accounts:register' %}" class="nav-link"> Sign Up </a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-link"> About </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    <h1 class="text-center my-5"> Welcome to PACS HIS RIS system </h1>

    <div class="container d-flex justify-content-center">
        <div class="card text-center mt-5 pt-5 shadow  bg-body rounded w-50 ">
            <div class="card-body ">
                <h5 class="card-title">Please Login or Sign up to continue</h5>
                <p class="card-text"> This authentication system is for protecting your data from breach. </p>
                <a href="{% url 'accounts:account_nav' %}" class="btn btn-primary"> Login </a>
                <a href="{% url 'accounts:register' %}" class="btn text-light" style="background-color: teal;"> Sign Up </a>
            </div>
        </div>
    </div>
    <footer class="my-5 py-5">
        <div class="bg-dark text-light mt-5 p-5 text-center">
            <div class="container">
                <h3>Devloped for Telemedicine Lab, BME, KUET</h3>
            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>

</html>