PACS_HIS_RIS/urls.py
from django.contrib import admin
from django.urls import path,include

admin.site.site_header = "PACS HIS RIS Admin"
admin.site.site_title = "PACS HIS RIS Admin Portal"
admin.site.index_title = "Welcome to PACS HIS RIS Admin Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("home_app.urls")),
    path("accounts/",include("accounts.urls")),
    path("patient/",include("patient.urls")),
    path("lab_operator/",include("lab_operator.urls")),
    path("doctor/",include("doctor.urls")),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path,include
from .views import register_request,login_request,logout_request,account_nav
app_name = "accounts"
urlpatterns = [
    path("register", register_request, name="register"),
    path("login", login_request, name="login"),
    path("account_nav", account_nav, name="account_nav"),
    path("logout", logout_request, name="logout"),
]

doctor/urls.py
from django.urls import path
from .views import doctor_dashboard,prescribe,patient_not_found,previous_prescription,previous_prescriptions_details

app_name = "doctor"
urlpatterns = [
    path("dashboard",doctor_dashboard,name="doctor_dashboard"),
    path("prescribe",prescribe,name="prescribe"),
    path("patient_not_found",patient_not_found,name="patient_not_found"),
    path("previuos_prescriptions",previous_prescription,name="previous_prescription"),
    path("previuos_prescriptions_details/<int:id>",previous_prescriptions_details,name="previous_prescriptions_details"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    first_name = models.CharField(max_length=50,blank=False,null=False,help_text ="Please Enter Your First Name")
    last_name = models.CharField(max_length=50,blank=False,null=False,help_text ="Please Enter Your Last/Given Name")
    phone = models.CharField(max_length=11,blank=False,null=False,primary_key=True,help_text ="Please Enter Your Phone number. eg: 01700000000")
    address = models.CharField(max_length=200,blank=False,null=False,help_text ="Please Enter Your Residential Address")
    gender = models.CharField(choices=[("M","Male"),("F","Female"),("Other","Other")],blank=False,null=False,max_length=10)
    blood_group = models.CharField(choices=[("A+","A+"),("A-","A-"),("B+","B+"),("B-","B-"),("AB+","AB+"),("AB-","AB-"),("O+","O+"),("O-","O-")],max_length=5)
    is_doctor = models.BooleanField(default=False,verbose_name="Is a Doctor")
    is_labop = models.BooleanField(default=False,verbose_name="Is a Lab Operator")


    def __str__(self):
        return  self.first_name + "_using_"  + self.phone

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ('first_name','last_name',"username", "email",'phone','address','gender','blood_group', "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

accounts/views.py
from django.shortcuts import  render, redirect
from .forms import NewUserForm
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm

def register_request(request):
    # return HttpResponse("Connected!")
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful." )
            return redirect("home_app:home")
    messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request,"accounts/register.html",{"register_form":form})



def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				# return redirect("patient:patient_dashboard")
				return redirect(request.GET.get('next'))
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="accounts/login.html", context={"login_form":form,"message":messages})



def account_nav(request):
	if request.method == "POST":
		patient_form = AuthenticationForm(request, data=request.POST)
		if patient_form.is_valid():
			
			username = patient_form.cleaned_data.get('username')
			password = patient_form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")

				if 'patient_login' in request.POST:
					return redirect("patient:patient_dashboard")
				elif 'doctor_login' in request.POST:
					return redirect("doctor:doctor_dashboard")
				elif 'operator_login' in request.POST:
					return redirect("lab_operator:labop_dashboard")



				# return redirect("patient:patient_dashboard")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	else:
		patient_form = AuthenticationForm()
		return render(request,"accounts/account_nav.html",{"patient_form":patient_form,"message":messages})


def logout_request(request):
    logout(request)

    messages.info(request, "You have successfully logged out.") 
    return redirect("home_app:home")

accounts/templates/accounts/account_nav.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Home </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" /> {% load static %}
    <link rel="stylesheet" href="{% static 'home_app/css/main.css' %}">

</head>

<body>
    {% load crispy_forms_tags %}
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
            <a href="../../../" class="navbar-brand"> PACS HIS RIS System</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu">
                <span class="navabar-toggler-icon"> <i class="fas fa-bars"></i></span>
            </button>

            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="{% url 'accounts:account_nav' %}" class="nav-link"> Login </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'accounts:register' %}" class="nav-link"> Sign Up </a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-link"> About </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    <h1 class="text-black-50 text-center mt-5 "> Please Specify Yourself as: </h1>


    <!-- RH: this is bootstrap 5 tabbed panel -->

    <div class="container d-flex justify-content-center mt-5">
        <div class="card py-5 shadow bg-body rounded w-75">
            <ul class="nav nav-tabs d-flex justify-content-around" id="myTab" role="tablist">
                <li class="nav-item" role="presentation">
                    <a class="nav-link active" id="home-tab" data-bs-toggle="tab" href="#patient" role="tab" aria-controls="patient" aria-selected="true">Patient</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link" id="profile-tab" data-bs-toggle="tab" href="#doctor" role="tab" aria-controls="doctor" aria-selected="false">Doctor</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link" id="contact-tab" data-bs-toggle="tab" href="#operator" role="tab" aria-controls="operator" aria-selected="false">Lab Operator</a>
                </li>
            </ul>
            <!-- tab content -->
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="patient" role="tabpanel" aria-labelledby="home-tab">

                    <form method="POST" class="p-5">
                        {% csrf_token %} {{ patient_form|crispy }}
                        <button class="btn btn-primary mt-3" type="submit" name="patient_login">Login</button>
                    </form>
                    <p class="text-center"> Don't have an account? <a href="{% url 'accounts:register' %}">Create an account</a>.</p>

                </div>
                <div class="tab-pane fade" id="doctor" role="tabpanel" aria-labelledby="doctor-tab">

                    <form method="POST" class="p-5"> {% csrf_token %} {{ patient_form|crispy }}
                        <button class="btn btn-primary mt-3" type="submit" name="doctor_login">Login</button>
                    </form>
                    <p class="text-center"> Don't have an account? <a href="{% url 'accounts:register' %}">Create an account</a>.</p>

                </div>
                <div class="tab-pane fade" id="operator" role="tabpanel" aria-labelledby="operator-tab">

                    <form method="POST" class="p-5"> {% csrf_token %} {{ patient_form|crispy }}
                        <button class="btn btn-primary mt-3" type="submit" name="operator_login">Login</button>
                    </form>
                    <p class="text-center"> Don't have an account? <a href="{% url 'accounts:register' %}">Create an account</a>.</p>
                </div>
            </div>
        </div>
    </div>



    <footer class="my-5 py-5 ">
        <div class="bg-dark text-light mt-5 p-5 text-center">
            <div class="container">
                <h3>Devloped for Telemedicine Lab, BME, KUET</h3>
            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>

</html>

accounts/templates/accounts/login.html
{% extends "base.html" %} {% block content %} {% load crispy_forms_tags %}

<!--Login-->
<div class="container py-5">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %} {{ login_form|crispy }}
        <button class="btn btn-primary" type="submit">Login</button>
    </form>
    <p class="text-center"> Don't have an account? <a href="{% url 'accounts:register' %}">Create an account</a>.</p>
</div>

{% endblock %}

accounts/templates/accounts/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Home </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" /> {% load static %}
    <link rel="stylesheet" href="{% static 'home_app/css/main.css' %}">

</head>

<body>
    {% load crispy_forms_tags %}
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
            <a href="../../../" class="navbar-brand"> PACS HIS RIS System</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu">
                <span class="navabar-toggler-icon"> <i class="fas fa-bars"></i></span>
            </button>

            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="{% url 'accounts:account_nav' %}" class="nav-link"> Login </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'accounts:register' %}" class="nav-link"> Sign Up </a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-link"> About </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>





    <!-- RH: this is bootstrap 5 tabbed panel -->

    <div class=" d-flex justify-content-center mt-5">
        <div class="container card p-5 shadow bg-body rounded w-75">
            <!--Register-->
            <h1>Please Register with proper information:</h1>
            <form method="POST">
                {% csrf_token %} {{ register_form|crispy }}
                <button class="btn btn-primary" type="submit">Register</button>
            </form>
            <p class="text-center">If you already have an account, <a href="{% url 'accounts:login' %}">login</a> instead.</p>
        </div>
    </div>



    <footer class="my-5 py-5 ">
        <div class="bg-dark text-light mt-5 p-5 text-center">
            <div class="container">
                <h3>Devloped for Telemedicine Lab, BME, KUET</h3>
            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>

</html>