PACS_HIS_RIS/urls.py
from django.contrib import admin
from django.urls import path,include

admin.site.site_header = "PACS HIS RIS Admin"
admin.site.site_title = "PACS HIS RIS Admin Portal"
admin.site.index_title = "Welcome to PACS HIS RIS Admin Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("home_app.urls")),
    path("accounts/",include("accounts.urls")),
    path("patient/",include("patient.urls")),
    path("lab_operator/",include("lab_operator.urls")),
    path("doctor/",include("doctor.urls")),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctor/urls.py
from django.urls import path
from .views import doctor_dashboard,prescribe,patient_not_found,previous_prescription,previous_prescriptions_details

app_name = "doctor"
urlpatterns = [
    path("dashboard",doctor_dashboard,name="doctor_dashboard"),
    path("prescribe",prescribe,name="prescribe"),
    path("patient_not_found",patient_not_found,name="patient_not_found"),
    path("previuos_prescriptions",previous_prescription,name="previous_prescription"),
    path("previuos_prescriptions_details/<int:id>",previous_prescriptions_details,name="previous_prescriptions_details"),
]

patient/urls.py
from django.urls import path
from .views import patient_dashboard,patient_records,patient_rad_records
from django.contrib import admin



app_name = "patient"
urlpatterns = [
    path("dashboard",patient_dashboard,name="patient_dashboard"),
    path("patient_records",patient_records,name="patient_records"),
    path("patient_rad_records",patient_rad_records,name="patient_rad_records"),
]

patient/models.py
from django.db import models

# Create your models here.

patient/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from doctor.models import Prescription
from lab_operator.models import Radiological_Data

@login_required(login_url="/../accounts/login")
def patient_dashboard(request):
    username = request.user.username
    return render(request,"patient/dashboard.html",{"username":username})

def patient_records(request):
    patient = request.user
    patient_name = patient.username
    prescriptions = Prescription.objects.filter(patient=patient)

    return render(request,"patient/patient_records.html",{"prescriptions":prescriptions,"patient_name":patient_name})


def patient_rad_records(request):
    patient = request.user
    patient_name = patient.username
    rad_datas = Radiological_Data.objects.filter(patient=patient)

    return render(request,"patient/patient_rad_records.html",{"rad_datas":rad_datas,"patient_name":patient_name})

patient/templates/patient/dashboard.html
{% extends "base.html" %} {% block content %}

<h1 class="text-center"> Hello {{username}}! </h1>


<div class=" d-flex justify-content-center mt-5">
    <div class="container card p-5 shadow bg-body rounded w-75 text-center">
        <!--Register-->
        <h3 class="my-5"> Welcome to your dashboard! </h3>
        <p class=""> You can Browse your Medical Records from Here. </p>

        <div class="card-body d-flex justify-content-around mt-5">
            <button class="btn btn-success rounded-pill py-3 px-5 hover-zoom"><a href="{% url 'patient:patient_records' %}" class="text-decoration-none text-white"> Previous Medical Records </a></button>
            <button class="btn btn-success rounded-pill py-3 px-5 hover-zoom"><a href="{% url 'patient:patient_rad_records' %}" class="text-decoration-none text-white"> Previous Radiological Records </a></button>
        </div>

    </div>
</div>
{% endblock %}

patient/templates/patient/patient_rad_records.html
<style>
    #prescriptions {
        font-family: Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }
    
    #prescriptions td,
    #prescriptions th {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: center;
    }
    
    #prescriptions tr:nth-child(even) {
        background-color: #f2f2f2;
    }
    
    #prescriptions tr:hover {
        background-color: #ddd;
    }
    
    #prescriptions th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #04AA6D;
        color: white;
    }
</style>


{% extends "base.html" %} {% block content %}

<center>
    <h1 class="my-5 p-5"> Radiological Records of {{patient_name}} </h1>
</center>



<div class="container card p-5 shadow bg-body rounded w-75">
    <table width=80% id="prescriptions">
        <tr>
            <th> Experiment Name </th>
            <th> Visit Date</th>
            <th> View Details </th>

        </tr>
        {% for rad_data in rad_datas %}


        <tr>
            <td> {{ rad_data.experiment_name }} </td>
            <td> {{ rad_data.upload_date }} </td>
            <td> <button class="btn btn-dark"><a href="../..{{ rad_data.get_absolute_url }}" class="text-decoration-none text-white"> View </a></button> </td>
        </tr>

        {% endfor %}
    </table>

    <div class="wrap d-flex justify-content-center">
        <button onclick="goBack()" class="btn btn-dark mt-5 rounded-pill col-md-6">Go Back</button>
    </div>
</div>
<script>
    function goBack() {
        window.history.back();
    }
</script>


{% endblock %}

patient/templates/patient/patient_records.html
<style>
    #prescriptions {
        font-family: Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }
    
    #prescriptions td,
    #prescriptions th {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: center;
    }
    
    #prescriptions tr:nth-child(even) {
        background-color: #f2f2f2;
    }
    
    #prescriptions tr:hover {
        background-color: #ddd;
    }
    
    #prescriptions th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #04AA6D;
        color: white;
    }
</style>


{% extends "base.html" %} {% block content %}

<center>
    <h1 class="my-5 p-5"> Patient Records of {{patient_name}} </h1>
</center>


<div class="container card p-5 shadow bg-body rounded w-75">
    <table width=80% id="prescriptions">
        <tr>
            <th> Doctor Name </th>
            <th> Visit Date</th>
            <th> View Details </th>

        </tr>
        {% for prescription in prescriptions %}


        <tr>
            <td> {{ prescription.doctor.first_name }} {{ prescription.doctor.last_name }} </td>
            <td> {{ prescription.date }} </td>
            <td> <button class="btn btn-dark"><a href="../..{{ prescription.get_absolute_url }}" class="text-decoration-none text-white"> View </a></button> </td>
        </tr>



        {% endfor %}
    </table>

    <div class="wrap d-flex justify-content-center">
        <button onclick="goBack()" class="btn btn-dark mt-5 rounded-pill col-md-6">Go Back</button>
    </div>
</div>
<script>
    function goBack() {
        window.history.back();
    }
</script>





<div class="container">

</div>

{% endblock %}