PACS_HIS_RIS/urls.py
from django.contrib import admin
from django.urls import path,include

admin.site.site_header = "PACS HIS RIS Admin"
admin.site.site_title = "PACS HIS RIS Admin Portal"
admin.site.index_title = "Welcome to PACS HIS RIS Admin Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("home_app.urls")),
    path("accounts/",include("accounts.urls")),
    path("patient/",include("patient.urls")),
    path("lab_operator/",include("lab_operator.urls")),
    path("doctor/",include("doctor.urls")),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctor/urls.py
from django.urls import path
from .views import doctor_dashboard,prescribe,patient_not_found,previous_prescription,previous_prescriptions_details

app_name = "doctor"
urlpatterns = [
    path("dashboard",doctor_dashboard,name="doctor_dashboard"),
    path("prescribe",prescribe,name="prescribe"),
    path("patient_not_found",patient_not_found,name="patient_not_found"),
    path("previuos_prescriptions",previous_prescription,name="previous_prescription"),
    path("previuos_prescriptions_details/<int:id>",previous_prescriptions_details,name="previous_prescriptions_details"),
]

lab_operator/urls.py
from django.urls import path
from .views import labop_dashboard,upload_entry,previous_entries,previous_entry_details

app_name = "lab_operator"
urlpatterns = [
    path("dashboard",labop_dashboard,name="labop_dashboard"),
    path("upload_new",upload_entry,name="new_upload"),
    path("previous_entries",previous_entries,name="previous_entries"),
    path("previous_entry_details/<int:id>",previous_entry_details,name="previous_entry_details"),
]

lab_operator/models.py
from django.db import models
from accounts.models import User
from django.urls import reverse
from datetime import datetime,date
import os
import uuid
import random

def user_directory_path(instance, filename):
    # Get Current Date
    todays_date = datetime.now()

    path = "dicom/{}/{}/{}/".format(todays_date.year, todays_date.month, todays_date.day)
    extension = "." + filename.split('.')[-1]
    stringId = str(uuid.uuid4())
    randInt = str(random.randint(10, 99))

    # Filename reformat
    filename_reformat = stringId + randInt + extension

    return os.path.join(path, filename_reformat)

class Radiological_Data(models.Model):
    patient = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name="Patient Assigned",related_name="data_of_patient")
    operator = models.ForeignKey(User,on_delete=models.CASCADE,related_name="uploaded_by_operator")
    
    experiment_name = models.CharField(max_length=200,verbose_name="Experiment Name",blank=False,null=False)
    patient_history = models.CharField(max_length=10000,verbose_name="Patient History",blank=False,null=False)
    procedure = models.CharField(max_length=10000,verbose_name="Experiment Procedure",blank=False,null=False)
    findings = models.CharField(max_length=10000,verbose_name="Findings",blank=False,null=False)
    impression = models.CharField(max_length=10000,verbose_name="Impression",blank=True,null=True)
    file = models.FileField(upload_to=user_directory_path)
    upload_date =  models.DateField(default=str(date.today()),editable=False)
   
   
   
    def __str__(self):
        filename = str(self.patient)  + " by " + str(self.operator) + " at "+ str(self.upload_date)
        return filename
   

    def get_absolute_url(self):

        args=[ self.id ]

        return reverse('lab_operator:previous_entry_details', args=args )

lab_operator/forms.py
from django import forms
from .models import Radiological_Data
class UploadEntryForm(forms.ModelForm):

    class Meta:
        model= Radiological_Data
        fields = ('patient','experiment_name','patient_history','procedure','findings','impression','file')

lab_operator/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render
from .forms import UploadEntryForm
from accounts.models import User
from .models import Radiological_Data
import datetime
from django.contrib import messages
import mimetypes
import os

@login_required(login_url="/../accounts/login")
def labop_dashboard(request):
    username = request.user.username

    if request.user.is_labop:
        return render(request,"lab_operator/dashboard.html",{"username":username})
    else:
        return HttpResponse("You are not allowed to see this page!")



@login_required(login_url="/../accounts/login")
def upload_entry(request):

    if request.user.is_labop:
        if request.method == "POST":
            form = UploadEntryForm(request.POST,request.FILES)

            if form.is_valid:
                
                patient = request.POST.get("patient")
                patient = User.objects.get(phone=patient)
                operator = request.user
                experiment_name = request.POST.get("experiment_name")
                patient_history = request.POST.get("patient_history")
                procedure = request.POST.get("procedure")
                findings = request.POST.get("findings")
                impression = request.POST.get("impression")
                file = request.FILES["file"]

                radiological_data = Radiological_Data(patient=patient,operator=operator,experiment_name=experiment_name,patient_history=patient_history,procedure=procedure,findings=findings,impression=impression,file=file)

                radiological_data.save()
                return redirect("lab_operator:labop_dashboard")

            else:
                return redirect("doctor:patient_not_found")
        else:
            form = UploadEntryForm()
        return render(request,"lab_operator/upload_new.html",{"form":form})
    else:
        return redirect("patient:patient_dashboard")



@login_required(login_url="/../accounts/login")
def previous_entries(request):
    if request.user.is_labop:
        print("I'm here")
        print(request.user)
        entries = Radiological_Data.objects.filter(operator= request.user)
        print(entries)
        return render(request,"lab_operator/previous_uploads.html",{"entries":entries})
    else:
        print("I'm there")
        return redirect("patient:patient_dashboard")



@login_required(login_url="/../accounts/login")
def previous_entry_details(request,id):
    if request.user.is_labop:
        entry = Radiological_Data.objects.get(id=id)

        download_path =  "media/" + str(entry.file)

        return render(request,"lab_operator/previous_upload_details.html",{"entry":entry,"download_path":download_path})
    else:
        entry = Radiological_Data.objects.get(id=id)

        if entry.patient == request.user:
            
            download_path =  "media/" + str(entry.file)

            return render(request,"lab_operator/previous_upload_details.html",{"entry":entry,"download_path":download_path})
        else:
            return redirect("patient:patient_dashboard")

lab_operator/templates/lab_operator/dashboard.html
{% extends "base.html" %} {% block content %}



<h1 class="text-center"> Hello {{username}}! </h1>


<div class=" d-flex justify-content-center mt-5">
    <div class="container card p-5 shadow bg-body rounded w-75 text-center">
        <!--Register-->
        <h3 class="my-5"> Welcome to your operator dashboard! </h3>
        <p class=""> You can Upload and View your uploaded Records from Here. </p>

        <div class="card-body d-flex justify-content-around mt-5">
            <button class="btn btn-success rounded-pill py-3 px-5 hover-zoom"><a href="{% url 'lab_operator:new_upload' %}" class="text-decoration-none text-white"> Upload New Entry</a></button>
            <button class="btn btn-success rounded-pill py-3 px-5 hover-zoom"><a href="{% url 'lab_operator:previous_entries' %}" class="text-decoration-none text-white"> Previous Entries </a></button>
        </div>

    </div>
</div>

{% endblock %}

lab_operator/templates/lab_operator/previous_upload_details.html
<style>
    #patient_details {
        font-family: Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 50%;
    }
    
    #patient_details td,
    #patient_details th {
        border: 1px solid #ddd;
        padding: 8px;
    }
    
    #patient_details tr:nth-child(even) {
        background-color: #f2f2f2;
    }
    
    #patient_details tr:hover {
        background-color: #ddd;
    }
    
    #patient_details th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #04AA6D;
        color: white;
    }
</style>


{% extends "base.html" %} {% block content %}

<center>
    <h3 class="my-5"> Details for Entry of {{entry.patient.first_name }} {{entry.patient.last_name }} created at: {{ entry.upload_date }}</h3>
</center>

<div class="container card p-5 shadow bg-body rounded w-75">
    <center>
        <table id="patient_details">
            <tr>
                <td> First Name: </td>
                <td> {{entry.patient.first_name}} </td>
            </tr>
            <tr>
                <td> Last Name: </td>
                <td> {{entry.patient.last_name}} </td>
            </tr>

            <tr>
                <td> Gender: </td>
                <td> {{entry.patient.gender}} </td>
            </tr>
            <tr>
                <td> Blood Group: </td>
                <td> {{entry.patient.blood_group}} </td>
            </tr>
            <tr>
                <td> Address: </td>
                <td> {{entry.patient.address}} </td>
            </tr>
            <tr>
                <td> experiment_name: </td>
                <td> {{entry.experiment_name}} </td>
            </tr>
            <tr>
                <td> patient_history: </td>
                <td> {{entry.patient_history}} </td>
            </tr>
            <tr>
                <td> procedure: </td>
                <td> {{entry.procedure}} </td>
            </tr>
            <tr>
                <td> findings: </td>
                <td> {{entry.findings}} </td>
            </tr>
            <tr>
                <td> impression: </td>
                <td> {{entry.impression}} </td>
            </tr>
            <tr>
                <td> file: </td>
                <!-- <td> {{ download_path }} </td> -->
                <td> <button class="btn btn-dark"> <a href="/../../{{ download_path }}" class="text-decoration-none text-white"> Download </a>  </button> </td>
            </tr>
        </table>
    </center>
</div>


{% endblock %}

lab_operator/templates/lab_operator/previous_uploads.html
<style>
    #prescriptions {
        font-family: Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }
    
    #prescriptions td,
    #prescriptions th {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: center;
    }
    
    #prescriptions tr:nth-child(even) {
        background-color: #f2f2f2;
    }
    
    #prescriptions tr:hover {
        background-color: #ddd;
    }
    
    #prescriptions th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #04AA6D;
        color: white;
    }
</style>

{% extends "base.html" %} {% block content %}

<h1 style="text-align: center; margin: 50px;"> Previous Entries </h1>


<div class="container card p-5 shadow bg-body rounded w-75">
    <table width=80% id="prescriptions">
        <<tr>
            <th>
                Patient Name
            </th>
            <th>
                Date
            </th>
            <th>

            </th>
            </tr>
            {% for entry in entries %}
            <tr>
                <td>
                    {{entry.patient.first_name}} {{entry.patient.last_name }}
                </td>
                <td>
                    {{entry.upload_date}}
                </td>
                <td>
                    <button class="btn btn-dark"> <a href="{{ entry.get_absolute_url }}" class="text-decoration-none text-white"> View </a></a></button>
                </td>
            </tr>


            {% endfor %}
    </table>

    <div class="wrap d-flex justify-content-center">
        <button onclick="goBack()" class="btn btn-dark mt-5 rounded-pill col-md-6">Go Back</button>
    </div>
</div>
<script>
    function goBack() {
        window.history.back();
    }
</script>






{% endblock %}

lab_operator/templates/lab_operator/upload_new.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}
<h1 style="text-align: center;margin: 50px;"> Upload New Data </h1>


<div class="container card p-5 shadow bg-body rounded w-75">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %} {{form|crispy}}
        <button class="btn btn-primary my-5" type="submit">  Upload </button>
    </form>
</div>

<div class="container">

    <div class="wrap d-flex justify-content-center">
        <button onclick="goBack()" class="btn btn-dark mt-5 rounded-pill col-md-6">Go Back</button>
    </div>
</div>
<script>
    function goBack() {
        window.history.back();
    }
</script>

{% endblock %}